# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import telemetry_pb2 as telemetry__pb2


class TelemetryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendUpdate = channel.unary_unary(
                '/telemetry.Telemetry/SendUpdate',
                request_serializer=telemetry__pb2.NavigationUpdate.SerializeToString,
                response_deserializer=telemetry__pb2.Empty.FromString,
                )


class TelemetryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendUpdate,
                    request_deserializer=telemetry__pb2.NavigationUpdate.FromString,
                    response_serializer=telemetry__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.Telemetry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Telemetry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/telemetry.Telemetry/SendUpdate',
            telemetry__pb2.NavigationUpdate.SerializeToString,
            telemetry__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
