# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\xbc\x01\n\x10NavigationUpdate\x12\x18\n\x10\x63urrent_position\x18\x01 \x03(\x02\x12\x17\n\x0f\x63urrent_heading\x18\x02 \x03(\x02\x12*\n\rtraveled_path\x18\x03 \x03(\x0b\x32\x13.telemetry.Position\x12!\n\x04path\x18\x04 \x03(\x0b\x32\x13.telemetry.Position\x12&\n\tobstacles\x18\x05 \x03(\x0b\x32\x13.telemetry.Position\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x07\n\x05\x45mpty2H\n\tTelemetry\x12;\n\nSendUpdate\x12\x1b.telemetry.NavigationUpdate\x1a\x10.telemetry.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NAVIGATIONUPDATE']._serialized_start=31
  _globals['_NAVIGATIONUPDATE']._serialized_end=219
  _globals['_POSITION']._serialized_start=221
  _globals['_POSITION']._serialized_end=253
  _globals['_EMPTY']._serialized_start=255
  _globals['_EMPTY']._serialized_end=262
  _globals['_TELEMETRY']._serialized_start=264
  _globals['_TELEMETRY']._serialized_end=336
# @@protoc_insertion_point(module_scope)
